POST http://localhost:4444/campaigns

{
    "name": "My campaign",
    "content": "My campaign content",
    "emails": ["test@test.com.br", "test2@test.com.br"]
}

###

GET http://localhost:4444/campaigns